// HTS 2-digit chapter → user-friendly name lookup. Based on the WCO HS
// Convention chapter titles, condensed to match the v11 mockup's tone.
// Chapter 77 is reserved (intentionally unused in HTS). Anything missing
// falls back to "Chapter NN" via getChapterName().
//
// Shared across surfaces:
//   - ProductCategoriesCard (Dashboard) — top-6 chapter table
//   - Historical Archive — top-25 chapter table
//   - Tariff Browser — chapter dropdown filter (uses HTS_CHAPTER_NAMES_LIST)

export const HTS_CHAPTER_NAMES: Record<string, string> = {
  "01": "Live animals",
  "02": "Meat",
  "03": "Fish and seafood",
  "04": "Dairy, eggs, honey",
  "05": "Other animal products",
  "06": "Live trees and plants",
  "07": "Vegetables",
  "08": "Fruit and nuts",
  "09": "Coffee, tea, spices",
  "10": "Cereals",
  "11": "Milling products",
  "12": "Oilseeds",
  "13": "Gums and resins",
  "14": "Vegetable plaiting materials",
  "15": "Fats and oils",
  "16": "Prepared meat and fish",
  "17": "Sugars",
  "18": "Cocoa",
  "19": "Cereal preparations",
  "20": "Prepared vegetables",
  "21": "Misc. edible preparations",
  "22": "Beverages and spirits",
  "23": "Animal feed",
  "24": "Tobacco",
  "25": "Salt, sulfur, stone",
  "26": "Ores and slag",
  "27": "Mineral fuels",
  "28": "Inorganic chemicals",
  "29": "Organic chemicals",
  "30": "Pharmaceuticals",
  "31": "Fertilizers",
  "32": "Dyes and tanning",
  "33": "Cosmetics and essential oils",
  "34": "Soaps and waxes",
  "35": "Albuminoidal substances",
  "36": "Explosives",
  "37": "Photographic goods",
  "38": "Misc. chemicals",
  "39": "Plastics",
  "40": "Rubber",
  "41": "Raw hides and leather",
  "42": "Leather goods",
  "43": "Furskins",
  "44": "Wood",
  "45": "Cork",
  "46": "Basketwork",
  "47": "Pulp",
  "48": "Paper",
  "49": "Printed books",
  "50": "Silk",
  "51": "Wool",
  "52": "Cotton",
  "53": "Other vegetable fibers",
  "54": "Man-made filaments",
  "55": "Man-made staple fibers",
  "56": "Wadding and nonwovens",
  "57": "Carpets",
  "58": "Special woven fabrics",
  "59": "Coated fabrics",
  "60": "Knitted fabrics",
  "61": "Apparel, knitted",
  "62": "Apparel, woven",
  "63": "Other textile articles",
  "64": "Footwear",
  "65": "Headgear",
  "66": "Umbrellas",
  "67": "Feathers and artificial flowers",
  "68": "Stone articles",
  "69": "Ceramic products",
  "70": "Glass",
  "71": "Pearls and precious stones",
  "72": "Iron and steel",
  "73": "Iron or steel articles",
  "74": "Copper",
  "75": "Nickel",
  "76": "Aluminum",
  // 77 is reserved (intentionally unused in HTS).
  "78": "Lead",
  "79": "Zinc",
  "80": "Tin",
  "81": "Other base metals",
  "82": "Tools and cutlery",
  "83": "Misc. base metal articles",
  "84": "Mechanical appliances",
  "85": "Electrical machinery",
  "86": "Railway equipment",
  "87": "Vehicles",
  "88": "Aircraft",
  "89": "Ships",
  "90": "Optical and medical instruments",
  "91": "Clocks and watches",
  "92": "Musical instruments",
  "93": "Arms and ammunition",
  "94": "Furniture and lamps",
  "95": "Toys and games",
  "96": "Misc. manufactured articles",
  "97": "Works of art",
  "98": "Special classifications",
  "99": "Temporary modifications",
};

/** Ordered list of `[code, name]` entries, sorted by code. Convenient for
 * rendering dropdowns or other ordered UI. */
export const HTS_CHAPTER_LIST: Array<[string, string]> = Object.entries(
  HTS_CHAPTER_NAMES,
).sort(([a], [b]) => a.localeCompare(b));

export function getChapterName(chapter: string): string {
  return HTS_CHAPTER_NAMES[chapter] ?? `Chapter ${chapter}`;
}
